# Generated by Django 4.2.20 on 2025-05-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pickup_location", models.CharField(max_length=100)),
                ("dropoff_location", models.CharField(max_length=100)),
                ("fare", models.DecimalField(decimal_places=2, max_digits=6)),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                ("is_claimed", models.BooleanField(default=False)),
            ],
        ),
    ]
